### ISSUE TITLE
Dead link (404)

### ISSUE THREAD

**Issue by tiborrr** [Sensirion/info#14]
link

https://github.com/Sensirion/embedded-common/tree/master/hw_i2c/sample-implementations

and 

https://github.com/Sensirion/embedded-common/tree/master/sw_i2c/sample-implementations

Do not exist anymore.

**Comment by winkj** [comment]
Thanks for the report, it looks like the i2c directories in embedded-common were renamed; updated in commit 8977ec5b80b471a02f985b6318513ab9370ebf3d
