### ISSUE TITLE
does this chip support intel ish？ do you have driver for this？

### ISSUE THREAD

**Issue by yanggengzhen** [Sensirion/info#25]

**Comment by yanggengzhen** [comment]
SH4X

**Comment by winkj** [comment]
Hi there,

We currently don't have a dedicated driver for the Intel sensor hub, but we have a generic driver that could be ported easily for anyone access to the ISH toolchain and docs: https://github.com/Sensirion/embedded-i2c-sht4x

Best, Johannes

**Comment by yanggengzhen** [comment]
> Hi there,
> 
> We currently don't have a dedicated driver for the Intel sensor hub, but we have a generic driver that could be ported easily for anyone access to the ISH toolchain and docs: https://github.com/Sensirion/embedded-i2c-sht4x
> 
> Best, Johannes

thanks for your reply
several more questions

1、Is this general driver developped based on ISH FDK？
2、any detail tutorial for driver ported to ISH？

thanks again

**Comment by psachs** [comment]
The embedded driver is a generic driver framework and not directly suitable to be used in intel integrated sensor hub. We also don't have our own linux kernel driver for SHT4x.
There is a 3rd party hwmon driver available for linux kernel which might be easier to port to ISH then the embedded driver:
https://code.googlesource.com/linux/torvalds/linux/+/eb66fb03a727cde0ab9b1a3858de55c26f3007da/drivers/hwmon/sht4x.c

As we don't have any experience with ISH we can't help you with porting drivers to ISH. Let us know if you have any question concerning the sensor interface or handling
