### ISSUE TITLE
Rust driver for SPS30 I2C

### ISSUE THREAD

**Issue by david-gherghita** [Sensirion/info#4]
Hello!

I would like to add a new driver for the SPS30 sensor for I2C to the section named "Third party repositories provided by our developer community".

The crates.io link is https://crates.io/crates/sps30-i2c and the github repo is https://github.com/david-gherghita/sps30-i2c-rs.

Thank you.

**Comment by rnestler** [comment]
Hi @david-gherghita 
You can just create a pull-request where you add your crate :slightly_smiling_face:
